// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * Greet
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string>}  - Go Type: string
       */
      "Greet": (arg1) => {
        return window.go.main.App.Greet(arg1);
      },
      /**
       * OpenQuestionnaire
       * @returns {Promise<Array<models.question>|Error>}  - Go Type: []*main.question
       */
      "OpenQuestionnaire": () => {
        return window.go.main.App.OpenQuestionnaire();
      },
      /**
       * Save
       * @param {Array<models.question>} arg1 - Go Type: []main.question
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "Save": (arg1) => {
        return window.go.main.App.Save(arg1);
      },
    },
  },

};
export default go;
